# Generated by Django 6.0.5 on 2026-06-01 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Authority Approval'), ('approved', 'Approved / Live'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0)),
                ('total_floors', models.PositiveIntegerField(default=1)),
                ('completed_floors', models.PositiveIntegerField(default=0)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('handover_date', models.DateField(blank=True, null=True)),
                ('cover_color', models.CharField(default='#1a2a3a', max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=300)),
                ('materials_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('done', models.BooleanField(default=False)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('pct', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('area', models.CharField(blank=True, max_length=300)),
                ('video_type', models.CharField(choices=[('structure', 'Structure'), ('authority', 'Authority Inspection'), ('unit', 'Unit View'), ('amenity', 'Amenity')], default='structure', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Upload'), ('ready', 'Ready'), ('rec', 'Live / Recording')], default='pending', max_length=20)),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='projects/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('floor', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('unit_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('structure_complete', 'Structure Complete'), ('mep_in_progress', 'MEP In Progress'), ('finishing', 'Finishing'), ('ready', 'Ready for Handover'), ('handed_over', 'Handed Over')], default='structure_complete', max_length=30)),
                ('ready', models.BooleanField(default=False)),
                ('latest_video', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='projects.project')),
            ],
            options={
                'ordering': ['floor', 'unit'],
                'unique_together': {('project', 'floor', 'unit')},
            },
        ),
    ]
