// ── SHAFFAF Central Data Store ──
// Single source of truth for all pages.

window.SHAFFAF = window.SHAFFAF || {};
window.SHAFFAF = window.SHAFFAF;
var SHAFFAF = window.SHAFFAF;

// ────────────────────────────────────────────────
// SUBSCRIPTION PLANS
// ────────────────────────────────────────────────
SHAFFAF.PLANS = [
  {
    id: 'free',
    name: 'Basic',
    package: 0,
    period: 'Forever',
    badge: null,
    color: '#8A8880',
    features: [
      'Company profile listing',
      'Up to 3 active projects',
      'Standard search visibility',
      'Client inquiry inbox',
      'SHAFFAF badge (unverified)',
    ],
    limits: { projects: 3, blueprints: 5, teamMembers: 1 },
    cta: 'Get Started Free',
  },
  {
    id: 'pro',
    name: 'Pro',
    package: 499,
    period: 'per month',
    badge: 'Most Popular',
    color: '#C9A84C',
    features: [
      'Everything in Basic',
      'Up to 25 active projects',
      'UAE Authority verification badge',
      'Blueprint vault (50GB)',
      'Investor progress tracker',
      'Priority search placement',
      'Analytics dashboard',
      '3 team members',
    ],
    limits: { projects: 25, blueprints: 50, teamMembers: 3 },
    cta: 'Start Pro Trial',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    package: 1899,
    period: 'per month',
    badge: 'UAE Ready',
    color: '#52C07A',
    features: [
      'Everything in Pro',
      'Unlimited projects',
      'UAE authority / approval API integration',
      'UAE authority portal access',
      'Unlimited blueprint vault',
      'White-label investor portal',
      'Dedicated account manager',
      'Unlimited team members',
      'SLA 99.9% uptime',
      'Audit log export (GDPR)',
    ],
    limits: { projects: Infinity, blueprints: Infinity, teamMembers: Infinity },
    cta: 'Contact Sales',
  },
];

// ────────────────────────────────────────────────
// COMPANIES
// ────────────────────────────────────────────────
SHAFFAF.COMPANIES = [
  {
    id: 'c1', name: 'Al Fardan Construction LLC', category: 'commercial',
    emoji: '🏢', location: 'Marina District, UAE', projects: 47, rating: 4.9,
    reviews: 124, founded: 2008, verified: true, plan: 'enterprise',
    specialties: ['High-Rise', 'Commercial', 'Mixed-Use'],
    license: 'UAE-MUN-CON-2008-447',
    desc: 'Premium commercial construction with 15+ years of landmark projects across the UAE.',
    coverColor: '#1a2a3a',
  },
  {
    id: 'c2', name: 'GoldenBuild Renovations', category: 'renovation',
    emoji: '🔨', location: 'Business Bay', projects: 312, rating: 4.8,
    reviews: 88, founded: 2014, verified: true, plan: 'pro',
    specialties: ['Renovation', 'Fit-Out', 'Interior'],
    license: 'UAE-MUN-REN-2014-891',
    desc: 'End-to-end renovation specialists for residential and commercial spaces.',
    coverColor: '#1a1a2a',
  },
  {
    id: 'c3', name: 'Nakheel Infrastructure Partners', category: 'infrastructure',
    emoji: '🌉', location: 'Deira', projects: 28, rating: 5.0,
    reviews: 41, founded: 2006, verified: true, plan: 'enterprise',
    specialties: ['Infrastructure', 'Roads', 'Civil'],
    license: 'UAE-MUN-INF-2006-112',
    desc: 'Large-scale civil and infrastructure works across the UAE.',
    coverColor: '#1a2a1a',
  },
  {
    id: 'c4', name: 'Skyline Villas & Homes', category: 'residential',
    emoji: '🏠', location: 'Palm Jumeirah', projects: 89, rating: 4.7,
    reviews: 203, founded: 2011, verified: true, plan: 'pro',
    specialties: ['Villas', 'Townhouses', 'Residential'],
    license: 'UAE-MUN-RES-2011-334',
    desc: 'Luxury residential construction specializing in bespoke villas and townhouses.',
    coverColor: '#2a1a1a',
  },
  {
    id: 'c5', name: 'Element Interiors UAE', category: 'interior',
    emoji: '🛋️', location: 'DIFC', projects: 156, rating: 4.6,
    reviews: 317, founded: 2016, verified: true, plan: 'pro',
    specialties: ['Interior Design', 'Fit-Out', 'FF&E'],
    license: 'UAE-MUN-INT-2016-779',
    desc: 'Award-winning interior fit-out and FF&E procurement for premium projects.',
    coverColor: '#2a1a2a',
  },
  {
    id: 'c6', name: 'Axis MEP Engineering', category: 'commercial',
    emoji: '⚙️', location: 'JLT', projects: 71, rating: 4.8,
    reviews: 96, founded: 2010, verified: true, plan: 'pro',
    specialties: ['MEP', 'HVAC', 'Electrical'],
    license: 'UAE-MUN-MEP-2010-556',
    desc: 'Mechanical, electrical, and plumbing specialists for commercial and industrial.',
    coverColor: '#1a1e2a',
  },
  {
    id: 'c7', name: 'ArchForm Design Studio', category: 'interior',
    emoji: '🎨', location: 'DIFC', projects: 92, rating: 4.9,
    reviews: 143, founded: 2017, verified: true, plan: 'pro',
    specialties: ['Architecture', 'Interior', '3D Design'],
    license: 'UAE-MUN-ARC-2017-441',
    desc: 'Boutique architectural and interior design studio for luxury residential and hospitality.',
    coverColor: '#1e1a2a',
  },
  {
    id: 'c8', name: 'CrestBuild Residential', category: 'residential',
    emoji: '🏡', location: 'Palm Jumeirah', projects: 134, rating: 4.6,
    reviews: 228, founded: 2009, verified: true, plan: 'pro',
    specialties: ['Villas', 'Swimming Pools', 'Landscaping'],
    license: 'UAE-MUN-RES-2009-198',
    desc: 'Premium villa and luxury residential construction with full fit-out capability.',
    coverColor: '#2a1e1a',
  },
  {
    id: 'c9', name: 'Urban Steel & Structures', category: 'commercial',
    emoji: '🔩', location: 'Deira', projects: 39, rating: 4.4,
    reviews: 62, founded: 2007, verified: true, plan: 'free',
    specialties: ['Structural Steel', 'Warehouses', 'Industrial'],
    license: 'UAE-MUN-STR-2007-310',
    desc: 'Structural steel fabrication and erection for commercial and industrial builds.',
    coverColor: '#1e2020',
  },
  {
    id: 'c10', name: 'GreenSpace Landscaping', category: 'renovation',
    emoji: '🌿', location: 'JLT', projects: 280, rating: 4.7,
    reviews: 119, founded: 2015, verified: true, plan: 'free',
    specialties: ['Landscaping', 'Irrigation', 'Outdoor'],
    license: 'UAE-MUN-GRN-2015-662',
    desc: 'Full-service landscaping and outdoor design for residential and commercial.',
    coverColor: '#141e14',
  },

  {
    id: 'c13', name: 'Binghatti Developers', category: 'residential',
    emoji: '🏙️', location: 'Business Bay, UAE', projects: 1, rating: 4.9,
    reviews: 62, founded: 2008, verified: true, plan: 'enterprise',
    specialties: ['Residential', 'High-Rise', 'Off-Plan Tracker'],
    license: 'UAE-MUN-DEV-2008-404',
    desc: 'Real UAE off-plan developer profile connected to One by Binghatti, with floor progress, unit status, site video updates, milestones, and investor visibility.',
    coverColor: '#10263a',
  },
];

// ────────────────────────────────────────────────
// PROJECTS (with investor-facing progress data)
// ────────────────────────────────────────────────
SHAFFAF.PROJECTS = [

  {
    id: 'p99', companyId: 'c13',
    name: 'One by Binghatti',
    type: 'Off-plan Residential Tower',
    location: 'Business Bay, UAE',
    value: 'Verified',
    valueRaw: 300000000,
    startDate: '2024-01-01',
    endDate: '2026-12-31',
    status: 'active',
    totalFloors: 61,
    registeredUnits: 755,
    paymentPlan: '20% signing / 50% during construction / 30% on completion',
    completedFloors: 15,
    currentFloor: 16,
    fitoutFloors: [1, 2, 3, 4, 5, 6],
    progressPct: 24,
    defaultUnit: '0608',
    readinessLabel: 'Business Bay off-plan tower under construction',
    readinessNote: 'The buyer can see floor-level progress, unit status, latest video proof, material readiness, and pending handover steps before Q4 2026 completion.',
    emoji: '🏙️',
    coverColor: '#10263a',
    description: 'Live off-plan tracker for One by Binghatti in Business Bay. Official project details list studios to 4-bedroom homes, 61 residential floors, basement/podium/amenity levels, and Q4 2026 completion; buyers can follow floor, unit, video, material, and authority evidence.',
    milestones: [
      { name: 'Project registration and enabling works', done: true, date: '2024-03-01', pct: 100 },
      { name: 'Basement and podium structure', done: true, date: '2025-12-30', pct: 100 },
      { name: 'Residential tower structure floors 1-15', done: true, date: '2026-05-08', pct: 100 },
      { name: 'Residential tower structure floors 16-30', done: false, date: '2026-08-30', pct: 22 },
      { name: 'MEP and facade first-fix floors 1-12', done: false, date: '2026-09-30', pct: 38 },
      { name: 'Amenities, pool deck, and common areas', done: false, date: '2026-11-30', pct: 12 },
      { name: 'UAE Authority Final Inspection', done: false, date: '2026-12-15', pct: 0 },
      { name: 'Buyer Handover', done: false, date: '2026-12-31', pct: 0 },
    ],
    updates: [
      { date: '2026-05-08', text: 'Tracker aligned to the live public snapshot: One by Binghatti is under construction in Business Bay, with market tracking showing 24% construction progress.' },
      { date: '2026-05-07', text: 'Official project details confirm studios to 4-bedroom residences, 61 residential floors, basement/podium/amenity levels, and Q4 2026 completion guidance.' },
      { date: '2026-05-06', text: 'Floor 6 buyer view remains visible for the demo: structure evidence is available, while MEP, fit-out, and final inspection remain pending.' },
    ],
    videoUpdates: [
      { date: '08 May 2026', title: 'Business Bay tower progress overview', area: 'North crane view / structure team', duration: '01:42', status: 'REC', type: 'structure' },
      { date: '08 May 2026', title: 'Floor 6 corridor and unit 0608 status', area: 'Buyer unit proof / MEP rough-in', duration: '00:58', status: 'READY', type: 'authority' },
      { date: '07 May 2026', title: 'Podium and amenity floor evidence slot', area: 'Podium package / external elevation', duration: '01:16', status: 'READY', type: 'structure' },
      { date: '06 May 2026', title: 'UAE authority inspection evidence pack', area: 'QA/QC walk-through', duration: '02:04', status: 'READY', type: 'authority' },
    ],
    unitRecords: [
      {
        unit: '0608',
        floor: 6,
        type: '1-bedroom apartment',
        ready: false,
        status: 'Structure complete; MEP rough-in active; fit-out and final inspection pending.',
        structure: 'Complete',
        mep: 'Active',
        fitout: 'Pending',
        latestVideo: '08 May 2026 - Floor 6 corridor and unit 0608 status',
        note: 'Buyer can see that the floor exists and is progressing, but the unit is not ready for handover.'
      },
      {
        unit: '0612',
        floor: 6,
        type: 'Studio apartment',
        ready: false,
        status: 'Structure complete; blockwork and first-fix MEP active.',
        structure: 'Complete',
        mep: 'Active',
        fitout: 'Pending',
        latestVideo: '08 May 2026 - Floor 6 corridor and unit 0608 status',
        note: 'Floor-level inspection evidence is available; unit-specific snagging will appear later.'
      },
    ],
    authorityReview: [
      { label: 'Developer trade license', value: 'Verified', tone: 'green' },
      { label: 'Escrow / project registration', value: 'Linked', tone: 'green' },
      { label: 'Public construction progress', value: '24%', tone: 'gold' },
      { label: 'Registered units', value: '755', tone: 'green' },
      { label: 'Daily video evidence slots', value: 'Ready', tone: 'gold' },
      { label: 'Material submittal trail', value: 'Active', tone: 'green' },
      { label: 'Buyer document signing', value: 'Enabled', tone: 'green' },
      { label: 'Final UAE authority inspection', value: 'Pending', tone: 'muted' },
    ],
    investors: ['Demo Investor Group'],
    materials: [
      { item: 'Concrete / Ready Mix', source: 'UAE approved batching plant', supplier: 'Readymix / Unibeton-style approved supplier', documents: 'Mix design, cube tests, delivery notes' },
      { item: 'Reinforcement Steel', source: 'Emirates Steel Arkan', supplier: 'Certified UAE stockist', documents: 'Mill certificate, bar bending schedule' },
      { item: 'Facade / Glass / Aluminium', source: 'Guardian Glass / approved aluminium system', supplier: 'Facade subcontractor', documents: 'Shop drawings, warranty, inspection report' },
      { item: 'MEP Package', source: 'Ducab / Grundfos / approved HVAC package', supplier: 'Nominated MEP subcontractor', documents: 'Commissioning report and authority approvals' },
      { item: 'Finishes and Fixtures', source: 'Approved sample board and supplier schedule', supplier: 'Nominated fit-out supplier', documents: 'Material approvals, warranty cards, delivery notes' },
      { item: 'Payment Plan Reference', source: 'Developer public project page', supplier: 'Binghatti Developers', documents: '20% on signing, 50% during construction, 30% on completion' },
    ],
    budget: { total: 100, spent: 62, currency: 'readiness percent' },
  },
  {
    id: 'p1', companyId: 'c1',
    name: 'Horizon Tower — Business Bay',
    type: 'High-Rise Commercial',
    location: 'Business Bay, UAE',
    value: 'Verified',
    valueRaw: 480000000,
    startDate: '2023-03-01',
    endDate: '2026-06-01',
    status: 'active',
    totalFloors: 42,
    completedFloors: 18,
    progressPct: 43,
    emoji: '🏢',
    coverColor: '#0d1b2a',
    description: 'A landmark 42-floor mixed-use tower featuring Grade A office space, premium retail podium, and sky-lounge facilities. Delivered to full UAE municipal authority green-building standards.',
    milestones: [
      { name: 'Foundation & Piling',      done: true,  date: '2023-06-15', pct: 100 },
      { name: 'Basement Structure',        done: true,  date: '2023-09-20', pct: 100 },
      { name: 'Ground + Podium Floors',    done: true,  date: '2024-02-10', pct: 100 },
      { name: 'Tower Core (Floors 1-18)', done: true,  date: '2024-11-30', pct: 100 },
      { name: 'Tower Structure (19-30)',   done: false, date: '2025-06-30', pct: 35  },
      { name: 'Tower Structure (31-42)',   done: false, date: '2025-12-01', pct: 0   },
      { name: 'MEP Rough-In',              done: false, date: '2026-02-01', pct: 20  },
      { name: 'Fit-Out & Façade',          done: false, date: '2026-04-15', pct: 0   },
      { name: 'Handover',                  done: false, date: '2026-06-01', pct: 0   },
    ],
    updates: [
      { date: '2025-04-28', text: 'Floor 18 slab pour completed. Structural inspection passed. Moving to floor 19 formwork.' },
      { date: '2025-04-01', text: 'MEP rough-in started on floors 5–10. Electrical conduit installation 60% complete.' },
      { date: '2025-03-15', text: 'Curtain wall glazing commenced on floors 1–6. Structural steel for floors 15–18 erected.' },
    ],
    investors: ['Mohammed Al Rashid', 'UAE Capital Partners', 'Emaar Investments'],
    materials: [
      { item: 'Concrete / Ready Mix', source: 'UAE approved batching plant', supplier: 'Readymix / Unibeton-style approved supplier', documents: 'Mix design, cube tests, delivery notes' },
      { item: 'Reinforcement Steel', source: 'Emirates Steel Arkan', supplier: 'Certified UAE stockist', documents: 'Mill certificate, bar bending schedule' },
      { item: 'Facade / Glass / Aluminium', source: 'Guardian Glass / approved aluminium system', supplier: 'Facade subcontractor', documents: 'Shop drawings, warranty, inspection report' },
      { item: 'MEP Package', source: 'Ducab / Grundfos / approved HVAC package', supplier: 'Nominated MEP subcontractor', documents: 'Commissioning report and authority approvals' },
    ],
    budget: { total: 480, spent: 206, currency: 'material units' },
  },
  {
    id: 'p2', companyId: 'c1',
    name: 'Al Barsha Medical Center Expansion',
    type: 'Healthcare',
    location: 'Al Barsha, UAE',
    value: 'Verified',
    valueRaw: 120000000,
    startDate: '2022-01-10',
    endDate: '2024-08-01',
    status: 'complete',
    totalFloors: 8,
    completedFloors: 8,
    progressPct: 100,
    emoji: '🏥',
    coverColor: '#0a1a14',
    description: 'Eight-floor medical center expansion including specialist clinics, surgical suites, and diagnostic imaging. Delivered on time and with approved handover records.',
    milestones: [
      { name: 'Foundation',          done: true, date: '2022-04-01', pct: 100 },
      { name: 'Structure Complete',  done: true, date: '2022-10-15', pct: 100 },
      { name: 'MEP Installation',    done: true, date: '2023-04-20', pct: 100 },
      { name: 'Fit-Out',             done: true, date: '2023-11-01', pct: 100 },
      { name: 'Commissioning',       done: true, date: '2024-05-15', pct: 100 },
      { name: 'Handover',            done: true, date: '2024-08-01', pct: 100 },
    ],
    updates: [
      { date: '2024-08-01', text: 'Project fully handed over to DHA. Certificate of completion issued. All snagging cleared.' },
    ],
    investors: ['UAE Health Authority', 'Private Health Fund LLC'],
    materials: [
      { item: 'Concrete / Ready Mix', source: 'UAE approved batching plant', supplier: 'Readymix / Unibeton-style approved supplier', documents: 'Mix design, cube tests, delivery notes' },
      { item: 'Reinforcement Steel', source: 'Emirates Steel Arkan', supplier: 'Certified UAE stockist', documents: 'Mill certificate, bar bending schedule' },
      { item: 'Facade / Glass / Aluminium', source: 'Guardian Glass / approved aluminium system', supplier: 'Facade subcontractor', documents: 'Shop drawings, warranty, inspection report' },
      { item: 'MEP Package', source: 'Ducab / Grundfos / approved HVAC package', supplier: 'Nominated MEP subcontractor', documents: 'Commissioning report and authority approvals' },
    ],
    budget: { total: 120, spent: 118, currency: 'material units' },
  },
  {
    id: 'p3', companyId: 'c3',
    name: 'Sheikh Zayed Road Underpass — Phase 2',
    type: 'Infrastructure / Civil',
    location: 'Sheikh Zayed Road, UAE',
    value: 'Verified',
    valueRaw: 1100000000,
    startDate: '2024-01-01',
    endDate: '2027-03-01',
    status: 'active',
    totalFloors: 0,
    completedFloors: 0,
    progressPct: 22,
    emoji: '🌉',
    coverColor: '#0d1a0d',
    description: 'Major road infrastructure project: 3.2km underpass, 4-lane dual carriageway with smart traffic integration, and pedestrian bridges. authority-contracted.',
    milestones: [
      { name: 'Enabling Works & Survey',   done: true,  date: '2024-03-01', pct: 100 },
      { name: 'Excavation Phase 1',        done: true,  date: '2024-09-01', pct: 100 },
      { name: 'Excavation Phase 2',        done: false, date: '2025-06-01', pct: 55  },
      { name: 'Structural Concrete Works', done: false, date: '2025-12-01', pct: 10  },
      { name: 'Road Surfacing',            done: false, date: '2026-06-01', pct: 0   },
      { name: 'Smart Systems Install',     done: false, date: '2026-12-01', pct: 0   },
      { name: 'Testing & Commissioning',   done: false, date: '2027-02-01', pct: 0   },
      { name: 'Handover to UAE Authority',           done: false, date: '2027-03-01', pct: 0   },
    ],
    updates: [
      { date: '2025-04-20', text: 'Excavation Phase 2 progressing on schedule. 1.8km of 3.2km total length excavated.' },
      { date: '2025-03-01', text: 'Utility diversion completed on Section A. Dewatering system operational across full site.' },
    ],
    investors: ['UAE Authority', 'UAE Infrastructure Fund'],
    materials: [
      { item: 'Concrete / Ready Mix', source: 'UAE approved batching plant', supplier: 'Readymix / Unibeton-style approved supplier', documents: 'Mix design, cube tests, delivery notes' },
      { item: 'Reinforcement Steel', source: 'Emirates Steel Arkan', supplier: 'Certified UAE stockist', documents: 'Mill certificate, bar bending schedule' },
      { item: 'Facade / Glass / Aluminium', source: 'Guardian Glass / approved aluminium system', supplier: 'Facade subcontractor', documents: 'Shop drawings, warranty, inspection report' },
      { item: 'MEP Package', source: 'Ducab / Grundfos / approved HVAC package', supplier: 'Nominated MEP subcontractor', documents: 'Commissioning report and authority approvals' },
    ],
    budget: { total: 1100, spent: 242, currency: 'material units' },
  },
  {
    id: 'p4', companyId: 'c4',
    name: 'Palm Frond Villa — Plot J-14',
    type: 'Luxury Residential Villa',
    location: 'Palm Jumeirah, UAE',
    value: 'Verified',
    valueRaw: 22000000,
    startDate: '2024-08-01',
    endDate: '2025-12-01',
    status: 'active',
    totalFloors: 3,
    completedFloors: 1,
    progressPct: 38,
    emoji: '🏠',
    coverColor: '#1a0d0d',
    description: 'Bespoke 3-floor luxury villa on Palm Jumeirah. Ground floor entertainment, first floor living, second floor master suites. Private pool and landscaped garden.',
    milestones: [
      { name: 'Design & Permits',       done: true,  date: '2024-08-20', pct: 100 },
      { name: 'Foundation',             done: true,  date: '2024-10-15', pct: 100 },
      { name: 'Ground Floor Structure', done: true,  date: '2025-01-20', pct: 100 },
      { name: '1st Floor Structure',    done: false, date: '2025-04-01', pct: 70  },
      { name: '2nd Floor Structure',    done: false, date: '2025-06-15', pct: 0   },
      { name: 'Roof & Waterproofing',   done: false, date: '2025-08-01', pct: 0   },
      { name: 'MEP & Fit-Out',          done: false, date: '2025-10-01', pct: 0   },
      { name: 'Landscaping & Pool',     done: false, date: '2025-11-15', pct: 0   },
      { name: 'Handover',               done: false, date: '2025-12-01', pct: 0   },
    ],
    updates: [
      { date: '2025-04-25', text: '1st floor columns and beams erected. Slab formwork 70% complete. On schedule for pour next week.' },
      { date: '2025-03-20', text: 'Ground floor MEP rough-in completed. External blockwork 100% done.' },
    ],
    investors: ['Private Client'],
    materials: [
      { item: 'Concrete / Ready Mix', source: 'UAE approved batching plant', supplier: 'Readymix / Unibeton-style approved supplier', documents: 'Mix design, cube tests, delivery notes' },
      { item: 'Reinforcement Steel', source: 'Emirates Steel Arkan', supplier: 'Certified UAE stockist', documents: 'Mill certificate, bar bending schedule' },
      { item: 'Facade / Glass / Aluminium', source: 'Guardian Glass / approved aluminium system', supplier: 'Facade subcontractor', documents: 'Shop drawings, warranty, inspection report' },
      { item: 'MEP Package', source: 'Ducab / Grundfos / approved HVAC package', supplier: 'Nominated MEP subcontractor', documents: 'Commissioning report and authority approvals' },
    ],
    budget: { total: 22, spent: 8.4, currency: 'material units' },
  },
  {
    id: 'p5', companyId: 'c2',
    name: 'DIFC Gate Avenue Fit-Out — Retail Block C',
    type: 'Commercial Fit-Out',
    location: 'DIFC, UAE',
    value: 'Verified',
    valueRaw: 34000000,
    startDate: '2025-01-15',
    endDate: '2025-09-01',
    status: 'active',
    totalFloors: 2,
    completedFloors: 0,
    progressPct: 28,
    emoji: '🏪',
    coverColor: '#1a1020',
    description: 'Full fit-out of 4,200sqm retail and F&B block at DIFC Gate Avenue. Includes MEP, joinery, FF&E, and technology fit-out for 12 retail units.',
    milestones: [
      { name: 'Design Freeze',            done: true,  date: '2025-01-30', pct: 100 },
      { name: 'Demolition & Strip-Out',   done: true,  date: '2025-02-15', pct: 100 },
      { name: 'MEP First Fix',            done: false, date: '2025-04-30', pct: 60  },
      { name: 'Drywall & Ceilings',       done: false, date: '2025-05-31', pct: 20  },
      { name: 'MEP Second Fix',           done: false, date: '2025-06-30', pct: 0   },
      { name: 'Joinery & FF&E',           done: false, date: '2025-07-31', pct: 0   },
      { name: 'Snagging & Handover',      done: false, date: '2025-09-01', pct: 0   },
    ],
    updates: [
      { date: '2025-04-29', text: 'MEP first fix 60% complete across all units. HVAC ducting installed in units 1-8.' },
      { date: '2025-04-10', text: 'Demolition works 100% complete. Site hoarding removed from Gate Avenue frontage.' },
    ],
    investors: ['DIFC Retail Investors LLC', 'Gate Avenue Development'],
    materials: [
      { item: 'Concrete / Ready Mix', source: 'UAE approved batching plant', supplier: 'Readymix / Unibeton-style approved supplier', documents: 'Mix design, cube tests, delivery notes' },
      { item: 'Reinforcement Steel', source: 'Emirates Steel Arkan', supplier: 'Certified UAE stockist', documents: 'Mill certificate, bar bending schedule' },
      { item: 'Facade / Glass / Aluminium', source: 'Guardian Glass / approved aluminium system', supplier: 'Facade subcontractor', documents: 'Shop drawings, warranty, inspection report' },
      { item: 'MEP Package', source: 'Ducab / Grundfos / approved HVAC package', supplier: 'Nominated MEP subcontractor', documents: 'Commissioning report and authority approvals' },
    ],
    budget: { total: 34, spent: 9.5, currency: 'material units' },
  },
  {
    id: 'p6', companyId: 'c6',
    name: 'JVC Residential Complex — MEP Package',
    type: 'MEP Engineering',
    location: 'Jumeirah Village Circle, UAE',
    value: 'Verified',
    valueRaw: 18000000,
    startDate: '2024-11-01',
    endDate: '2026-02-01',
    status: 'active',
    totalFloors: 14,
    completedFloors: 5,
    progressPct: 34,
    emoji: '⚙️',
    coverColor: '#0a0d1a',
    description: 'Full MEP package for 14-floor residential tower in JVC. Includes HVAC, plumbing, electrical, fire alarm, BMS, and ELV systems.',
    milestones: [
      { name: 'Shop Drawings Approved',    done: true,  date: '2024-12-01', pct: 100 },
      { name: 'Basement MEP',              done: true,  date: '2025-01-15', pct: 100 },
      { name: 'Ground to Floor 5 MEP',    done: true,  date: '2025-03-30', pct: 100 },
      { name: 'Floor 6-10 MEP',           done: false, date: '2025-07-01', pct: 40  },
      { name: 'Floor 11-14 MEP',          done: false, date: '2025-10-01', pct: 0   },
      { name: 'Testing & Commissioning',  done: false, date: '2026-01-01', pct: 0   },
      { name: 'Handover',                 done: false, date: '2026-02-01', pct: 0   },
    ],
    updates: [
      { date: '2025-04-22', text: 'Floor 6-8 HVAC ducting 40% complete. Plumbing rough-in on track for floors 6-7.' },
      { date: '2025-03-30', text: 'Floors 1-5 MEP 100% complete. UAE authority inspection passed all systems.' },
    ],
    investors: ['Nakheel Properties', 'JVC Residential Fund'],
    materials: [
      { item: 'Concrete / Ready Mix', source: 'UAE approved batching plant', supplier: 'Readymix / Unibeton-style approved supplier', documents: 'Mix design, cube tests, delivery notes' },
      { item: 'Reinforcement Steel', source: 'Emirates Steel Arkan', supplier: 'Certified UAE stockist', documents: 'Mill certificate, bar bending schedule' },
      { item: 'Facade / Glass / Aluminium', source: 'Guardian Glass / approved aluminium system', supplier: 'Facade subcontractor', documents: 'Shop drawings, warranty, inspection report' },
      { item: 'MEP Package', source: 'Ducab / Grundfos / approved HVAC package', supplier: 'Nominated MEP subcontractor', documents: 'Commissioning report and authority approvals' },
    ],
    budget: { total: 18, spent: 6.1, currency: 'material units' },
  },
];

// Helper: get company by id
SHAFFAF.getCompany = id => SHAFFAF.COMPANIES.find(c => c.id === id);
SHAFFAF.getProject = id => SHAFFAF.PROJECTS.find(p => p.id === id);
SHAFFAF.getCompanyProjects = cid => SHAFFAF.PROJECTS.filter(p => p.companyId === cid);
