# Generated by Django 6.0.5 on 2026-06-01 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='documents/signed/')),
                ('signer_name', models.CharField(max_length=200)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('audit_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('signature_page', models.PositiveSmallIntegerField(default=1)),
                ('signature_x', models.FloatField(default=0.72)),
                ('signature_y', models.FloatField(default=0.78)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_documents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_documents', to='projects.project')),
            ],
        ),
    ]
